// Maps a public asset path like /projects/foo.jpg to its resized webp variants
// generated by scripts/resize-images.mjs into /resized/<dir>/<base>-<w>w.webp.
// Returns { src, srcSet } for <img>; src falls back to the mid variant.

const WIDTHS = {
    projects: [800, 400],
    about: [1200, 700, 350],
    awards: [800, 400],
};

export function resizedImage(path) {
    if (!path) return { src: "", srcSet: undefined };
    const match = path.match(/^\/(projects|about|awards)\/(.+)\.(jpe?g|png)$/i);
    if (!match) return { src: path, srcSet: undefined };
    const [, dir, base] = match;
    const widths = WIDTHS[dir];
    const urls = widths.map((w) => `/resized/${dir}/${base}-${w}w.webp ${w}w`);
    return {
        src: `/resized/${dir}/${base}-${widths[0]}w.webp`,
        srcSet: urls.join(", "),
    };
}
